# -*- coding: utf-8 -*
"""
Read and parse log files generated by 'IMU Viewer'.
Created on 2020-3-23
@author: Ocean
"""

import os
import sys
import datetime
import time
import math
import re

def merge(sn_folder):
    ''' 
    Read and parse log files generated by 'IMU Viewer'.
    And output csv file for simulation.

    Input: log folder which contains a series of txt files, such as :
            '_2003003008_20-27-23@02.03.50_4.txt'
            '_2003003008_20-27-23@02.03.50_5.txt'
            '_2003003008_20-27-23@02.03.50_7.txt'
            '_2003003008_20-27-23@02.03.50_6.txt'
            '_2003003008_20-27-23@02.03.50_2.txt'
            '_2003003008_20-27-23@02.03.50_3.txt'
            '_2003003008_20-27-23@02.03.50_1.txt'
    
    Output: a csv file used for simulation, format as:
            accel_x in [g]
            accel_y in [g]
            accel_z in [g]
            gyro_x in [deg/sec]
            gyro_y in [deg/sec]
            gyro_z in [deg/sec]
            mag_x in [G]
            mag_y in [G]
            mag_z in [G]
            roll in [deg]
            pitch in [deg]
            yaw in [deg]
            temperature
    '''
    for root, dirs, files in os.walk(sn_folder):
        prefix = files[0][0:files[0].rfind('_')+1] # eg. prefix = '_2003003008_20-27-23@02.03.50_'
        files_num = len(files) # make sure only log files under sn_folder.
        sn = files[0].split('_')[1]
        root_path = root
        break
    
    files = []
    for i in range(files_num):
        files.append(os.path.join(root_path ,prefix + str(i) + '.txt'))

    if not os.path.exists('data/'):
        os.mkdir('data/')

    log_file_name = os.path.join('data', 'mergeA1_{0}_sim.csv'.format(sn))
    print('Start logging:{0}'.format(log_file_name))
    log_file = open(log_file_name, 'w')

    header_num = 8
    for file in files:
        with open(file, 'r') as f:
            idx = 0
            line = f.readline()

            while line:
                try:
                    idx += 1
                    if idx < header_num: # skip header
                        line = f.readline()
                        continue                    

                    if idx % 100000 == 0:
                        print(idx)
                        
                    data = line.split('\t')
                    time = data[0] # time stamp
                    temp = float(data[1]) # temperature
                    ax = float(data[2]) # accel_x in [g]
                    ay = float(data[3]) # accel_y in [g]
                    az = float(data[4]) # accel_z in [g]
                    gx = float(data[5]) # gyro_x in [deg/sec]
                    gy = float(data[6]) # gyro_y in [deg/sec]
                    gz = float(data[7]) # gyro_z in [deg/sec]
                    roll = float(data[8]) # [deg]
                    pitch = float(data[9]) # [deg]
                    yaw = float(data[10]) # [deg]
                    mx = float(data[11]) # mag_x
                    my = float(data[12]) # mag_y
                    mz = float(data[13]) # mag_z
                    mBIT = float(data[14])

                    if idx == 8: # print file name and first line
                        print(file, ":", time)

                    s = '{0:f},{1:f},{2:f},{3:f},{4:f},{5:f},  \
                        {6:f},{7:f},{8:f},{9:f},{10:f},{11:f},{12:f}'  \
                        .format(ax, ay, az, gx, gy, gz,      \
                            mx, my, mz, roll, pitch, yaw, temp).replace(' ', '')

                    log_file.write(s + '\n')
                    log_file.flush()
                    line = f.readline()

                except Exception as e:
                    print('Error at line {0} :{1}'.format(idx,e))
                    line = f.readline()


if __name__ == '__main__':
    sn_folder = r'/Users/songyang/project/analyze/factory/fail_analyze/305D_4units_A1_LOG_20200326/1903046161'
    merge(sn_folder)

